language: r
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
      # dist: xcode8
      brew_packages: valgrind
      latex: false
    # - os: osx
    #   r: devel
    #   dist: xcode8
    #   brew_packages: valgrind
    #   latex: false

addons:
  apt:
    packages:
    - valgrind

r_check_args: '--use-valgrind'

r_packages:
  - Rcpp
  - RcppEigen
  - BH

notifications:
  email:
    - turgeon.maxime@gmail.com
