language: r
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      dist: xcode8

addons:
  apt:
    packages:
    - valgrind

r_check_args: '--use-valgrind'

r_binary_packages:
  - Rcpp
  - RcppEigen
  - BH

notifications:
  email:
    - maxime.turgeon@mail.mcgill.ca
