language: r
r:
  - release
  - devel
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      dist: xcode8
      brew_packages: valgrind
      latex: false

addons:
  apt:
    packages:
    - valgrind

r_check_args: '--use-valgrind'

r_packages:
  - Rcpp
  - RcppEigen
  - BH

notifications:
  email:
    - maxime.turgeon@mail.mcgill.ca
