// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// doubleWishart_raw
NumericVector doubleWishart_raw(NumericVector x, int s, double m, double n, bool mp);
RcppExport SEXP rootWishart_doubleWishart_raw(SEXP xSEXP, SEXP sSEXP, SEXP mSEXP, SEXP nSEXP, SEXP mpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< bool >::type mp(mpSEXP);
    __result = Rcpp::wrap(doubleWishart_raw(x, s, m, n, mp));
    return __result;
END_RCPP
}
// singleWishart_raw
NumericVector singleWishart_raw(NumericVector x, int n_min, int n_max, bool mp);
RcppExport SEXP rootWishart_singleWishart_raw(SEXP xSEXP, SEXP n_minSEXP, SEXP n_maxSEXP, SEXP mpSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_min(n_minSEXP);
    Rcpp::traits::input_parameter< int >::type n_max(n_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type mp(mpSEXP);
    __result = Rcpp::wrap(singleWishart_raw(x, n_min, n_max, mp));
    return __result;
END_RCPP
}
