# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doubleWishart_C <- function(x, s, m, n) {
    .Call('rootWishart_doubleWishart_C', PACKAGE = 'rootWishart', x, s, m, n)
}

doubleWishart_raw <- function(x, s, m, n, mp) {
    .Call('rootWishart_doubleWishart_raw', PACKAGE = 'rootWishart', x, s, m, n, mp)
}

singleWishart_mpfr <- function(xx, n_min, n_max) {
    .Call('rootWishart_singleWishart_mpfr', PACKAGE = 'rootWishart', xx, n_min, n_max)
}

singleWishart_raw <- function(x, n_min, n_max, mp) {
    .Call('rootWishart_singleWishart_raw', PACKAGE = 'rootWishart', x, n_min, n_max, mp)
}

incompleteBeta_C <- function(x, alpha, beta) {
    .Call('rootWishart_incompleteBeta_C', PACKAGE = 'rootWishart', x, alpha, beta)
}

mgamma_C <- function(x, m, logar) {
    .Call('rootWishart_mgamma_C', PACKAGE = 'rootWishart', x, m, logar)
}

