# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doubleWishart <- function(x, s, m, n) {
    .Call('rootWishart_doubleWishart', PACKAGE = 'rootWishart', x, s, m, n)
}

incompleteBeta <- function(x, alpha, beta) {
    .Call('rootWishart_incompleteBeta', PACKAGE = 'rootWishart', x, alpha, beta)
}

